source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CCNetWorking_Example', :exclusive => true do
  pod "CCNetWorking", :path => "../"
end

target 'CCNetWorking_Tests', :exclusive => true do
  pod "CCNetWorking", :path => "../"

  
end
